### PR TITLE
Remote Device Reboots

### PR DESCRIPTION
**Pull request by versx**
Enables a http listener to receive remote device reboot requests either via DCM, RDMMonitor, or another method.
Endpoint is `/restart` (change to just `/`??) and expected post body payload format is the following:
```json
{
    "type": "restart",
    "device": "DeviceName01"
}
```

### CODE REVIEW

**Comment by versx** [comment]
Please test...

**Comment by kamieniarz** [comment]
Works as intended with RDMMonitor PR6, thanks for that! Waiting for restarts now ;)

**Comment by versx** [comment]
> Works as intended with RDMMonitor PR6, thanks for that! Waiting for restarts now ;)

What do you mean, this does restarts.

**Comment by kamieniarz** [comment]
I ment game restarts.

**Comment by kamieniarz** [comment]
Anyway, would that be possible to add an option to restart SAM with command?

**Comment by versx** [comment]
> Anyway, would that be possible to add an option to restart SAM with command?

Sure, what's the command to do it again?

**Pull request merged**
